blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         views.BlogView.as_view(), name='blog_home'),
    path('create/',
         views.BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/update/',
         views.BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>/delete/',
         views.BlogDeleteView.as_view(), name='blog_delete'),
    path('<slug:slug>/',
         views.BlogDetailView.as_view(), name='blog_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
]

furnitures/urls.py
from django.urls import path
from . import views

app_name = 'furnitures'

urlpatterns = [
    path('', views.FurnitureView.as_view(), name='furn_main'),
    path('create/', views.FurnitureCreateView.as_view(), name='furn_create'),
]

web_project/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('furnitures/', include('furnitures.urls', namespace='furnitures')),
    path('', include('pages.urls', namespace='pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from furnitures import models


class CartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, widget=forms.HiddenInput())
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from django.views.decorators.http import require_POST
from furnitures import models
from . import forms
from .cart import Cart


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(models.FurnituresModel, id=product_id)
    form = forms.CartForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(models.FurnituresModel, id=product_id)
    cart.remove(product)
    return JsonResponse({'success': True})


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = forms.CartForm(
            initial={
                'quantity': item['quantity'],
                'update': True,
            }
        )
    return render(request, 'cart/detail_cart.html', {'cart': cart, })

templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Ваша корзина товаров</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена</th>
            <th>Полная цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with furniture=item.product %}
                <tr>
                    <td>
                        <a href="{{ furniture.get_absolute_url }}">
                            <img width="60" height="60" src="{{ furniture.image.url }}" alt=""/>
                        </a>
                    </td>
                    <td>{{ furniture.title }}</td>
                    <td>
                        <form action="{% url "cart:cart_add" furniture.id %}" method="post" class="add">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            {% csrf_token %}
                            <input type="submit" value="Обновить">
                        </form>
                    </td>
                    <td><a href="{% url "cart:cart_remove" furniture.id %}">Удалить</a></td>
                    <td class="num">{{ item.price }} $</td>
                    <td class="num">{{ item.total_price }} $</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} $</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "furnitures:furn_main" %}" class="btn">Продолжить Шопинг</a>
        <a href="#">Оформить заказ</a>
    </p>
{% endblock %}

templates/cart/detail_cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="h-100" style="background-color: #eee;">
        <div class="container h-100 py-5">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-10">

                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
                        <div>
                            <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!" class="text-body">price
                                <i
                                        class="fas fa-angle-down mt-1"></i></a></p>
                        </div>
                    </div>
                    {% for item in cart %}
                        {% with furniture=item.product %}
                            <div class="card rounded-3 mb-4 cart-item">
                                <div class="card-body p-4">
                                    <div class="row d-flex justify-content-between align-items-center">
                                        <div class="col-md-2 col-lg-2 col-xl-2">
                                            <a href="{{ furniture.get_absolute_url }}">
                                                <img
                                                        src="{{ furniture.image.url }}"
                                                        class="img-fluid rounded-3" alt="{{ furniture.title }}">
                                            </a>
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-3">
                                            <p class="lead fw-normal mb-2">{{ furniture.title }}</p>
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                            <button class="btn btn-link px-2"
                                                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                                <i class="bi bi-dash">
                                                </i>
                                            </button>

                                            <input id="form1" min="1" name="quantity" value="{{ item.quantity }}" max="{{ furniture.quantity }}"
                                                   type="number"
                                                   class="form-control form-control-sm text-center" readonly/>

                                            <button class="btn btn-link px-2"
                                                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                                                <i class="bi bi-plus"></i>
                                            </button>
                                        </div>
                                        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                            <h5 class="mb-0">${{ furniture.price }}</h5>
                                        </div>
                                        <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                            <button class="btn btn-outline-0 remove-item"
                                                    data-product-id="{{ furniture.pk }}">
                                                <i class="bi bi-trash-fill text-danger"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endwith %}
                    {% endfor %}


                    <div class="card mb-4">
                        <div class="card-body p-4 d-flex flex-row">
                            <div class="form-outline flex-fill">
                                <input type="text" id="form1" class="form-control form-control-lg"/>
                                <label class="form-label" for="form1">Discound code</label>
                            </div>
                            <button type="button" class="btn btn-outline-warning btn-lg ms-3">Apply</button>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const removeButtons = document.querySelectorAll('.remove-item');

            removeButtons.forEach(button => {
                button.addEventListener('click', function () {
                    const productId = button.getAttribute('data-product-id');

                    // Отправить запрос на удаление товара на сервер Django (используя fetch или другой метод)

                    fetch(`/cart/remove/${productId}/`, {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': getCookie('csrftoken'), // Передача CSRF-токена
                            'Content-Type': 'application/json',
                        },
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                // Успешно удалено с сервера
                                // Теперь удалите элемент из DOM
                                button.closest('.cart-item').remove();
                            } else {
                                // Обработка ошибки удаления, если необходимо
                            }
                        });
                });
            });

            // Функция для получения CSRF-токена из куки
            function getCookie(name) {
                const value = `; ${document.cookie}`;
                const parts = value.split(`; ${name}=`);
                if (parts.length === 2) return parts.pop().split(';').shift();
            }
        });

    </script>
{% endblock %}