blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         views.BlogView.as_view(), name='blog_home'),
    path('create/',
         views.BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/update/',
         views.BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>/delete/',
         views.BlogDeleteView.as_view(), name='blog_delete'),
    path('<slug:slug>/',
         views.BlogDetailView.as_view(), name='blog_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
]

furnitures/urls.py
from django.urls import path
from . import views

app_name = 'furnitures'

urlpatterns = [
    path('', views.FurnitureView.as_view(), name='furn_main'),
    path('create/', views.FurnitureCreateView.as_view(), name='furn_create'),
]

web_project/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('furnitures/', include('furnitures.urls', namespace='furnitures')),
    path('', include('pages.urls', namespace='pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furnitures/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator


# Create your models here.
class FurnituresModel(models.Model):
    title = models.CharField(max_length=50, unique=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(0)])
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    image = models.ImageField(upload_to='furniture_image')

    class Meta:
        verbose_name = 'Furniture'

    def get_absolute_url(self):
        return reverse('furnitures:furn_main')

furnitures/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from . import models
from cart import forms


# Create your views here.
class FurnitureView(ListView):
    model = models.FurnituresModel
    template_name = 'furnitures/furnitures.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_product_form'] = forms.CartForm(initial={
            'quantity': 1,
        })
        return context


class FurnitureCreateView(CreateView):
    model = models.FurnituresModel
    fields = '__all__'
    template_name = 'furnitures/furniture_create.html'

templates/furnitures/furniture_create.html
{% extends 'base.html' %}

{% block content %}
    <h2>Create furniture</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать">
    </form>
{% endblock %}

templates/furnitures/furnitures.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="furniture_section layout_padding">
        <div class="container">
            <div class="heading_container">
                <h2>
                    Our Furniture
                </h2>
                <p>
                    which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you
                    need to be sure there isn't an
                </p>
            </div>
            <div class="row">
                {% for furniture in furnituresmodel_list %}
                    <div class="col-md-6 col-lg-4">
                        <div class="box">
                            <div class="img-box">
                                <img src="{{ furniture.image.url }}">
                            </div>
                            <div class="detail-box">
                                <h5>
                                    {{ furniture.title }}
                                </h5>
                                <div class="price_box">
                                    <h6 class="price_heading">
                                        <span>$</span> {{ furniture.price }}
                                    </h6>
                                    <form method="post" action="{% url 'cart:cart_add' furniture.id %}">
                                        {% csrf_token %}
                                        {{ cart_product_form }}
                                        <input type="submit" value="Buy now">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}