blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         views.BlogView.as_view(), name='blog_home'),
    path('create/',
         views.BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/update/',
         views.BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>/delete/',
         views.BlogDeleteView.as_view(), name='blog_delete'),
    path('<slug:slug>/',
         views.BlogDetailView.as_view(), name='blog_detail'),
]

web_project/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('furnitures/', include('furnitures.urls', namespace='furnitures')),
    path('', include('pages.urls', namespace='pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from slugify import slugify


# Create your models here.
class BlogCreateModel(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название статьи')
    image = models.ImageField(upload_to='blog_image', verbose_name='Фото')
    slug = models.SlugField(unique=True)
    body = models.TextField(verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='author',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name_plural = 'Blog'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogCreateModel, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={
            'slug': self.slug,
        })

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import (ListView, CreateView, DetailView,
                                  UpdateView, DeleteView, TemplateView)

from . import models


# Create your views here.
class BlogView(ListView):
    model = models.BlogCreateModel
    template_name = 'blog/blog.html'


class BlogDetailView(DetailView):
    model = models.BlogCreateModel
    template_name = 'blog/detail.html'


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = models.BlogCreateModel
    fields = (
        'image',
        'title',
        'body',
    )
    template_name = 'blog/create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.BlogCreateModel
    fields = (
        'image',
        'title',
        'body',
    )
    template_name = 'blog/update.html'

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class BlogDeleteView(DeleteView):
    model = models.BlogCreateModel
    success_url = reverse_lazy('blog:blog_home')
    template_name = 'blog/delete.html'

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}




{% block class %}sub_page{% endblock %}
{% block content %}
    <section class="blog_section layout_padding">
        <div class="container">
            <div class="heading_container">
                <h2>
                    Blog
                </h2>
            </div>
            {% if user.is_authenticated %}
                <button onclick="location.href='{% url 'blog:blog_create' %}'" type="button"
                        class="btn btn-primary btn-lg d-block mx-auto"
                        style="background-color: rgba(255, 255, 255, 0); color: #000">Добавить публикацию
                </button>
            {% endif %}
            <div class="row">
                {% for blog in blogcreatemodel_list %}
                    <div class="col-md-6 col-lg-4 mx-auto">
                        <div class="box">
                            <div class="img-box">
                                <img width="200px" height="200px" src="{{ blog.image.url }}" alt="">
                            </div>
                            <div class="detail-box">
                                <h5>
                                    {{ blog.title|truncatechars:50 }}
                                </h5>
                                <p>
                                    {{ blog.description }}
                                </p>
                                <a href="{% url 'blog:blog_detail' blog.slug %}">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/blog/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center m-2 mb-4">Create blog</h2>
    <form class="text-center" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Создать">
    </form>
{% endblock %}

templates/blog/delete.html
{% extends 'base.html' %}

{% block content %}
    <p>Вы действительно хотите удалить публикацию?</p>
    <form method="post">
        {% csrf_token %}
        <button class="button btn-danger" type="submit">Удалить</button>
    </form>
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card mt-5">
                    <img src="{{ object.image.url }}" class="card-img-top" alt="{{ object.title }}">
                    <div class="card-body">
                        <h2 class="card-title">{{ object.title }}</h2>
                        <p class="card-text">{{ object.body }}</p>
                    </div>
                    <div class="card-footer text-muted text-right">
                        {{ object.created_at }} | {{ object.author }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if user.is_authenticated %}
        {% if user.id == object.author.id %}
            <p class="text-center mt-3">
                <a class="text-center" href="{% url 'blog:blog_update' object.slug %}">Edit |</a>
                <a href="{% url 'blog:blog_delete' object.slug %}">Delete</a>
            </p>
        {% endif %}
    {% endif %}


{% endblock %}

templates/blog/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="text-center m-3">
        <h2>Edit Blog</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Сохранить">
        </form>
    </div>
{% endblock %}