accounts/urls.py
from django.urls import path
from . import views

app_name = 'signup'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         views.BlogView.as_view(), name='blog_home'),
    path('create/',
         views.BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/update/',
         views.BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>/delete/',
         views.BlogDeleteView.as_view(), name='blog_delete'),
    path('<slug:slug>/',
         views.BlogDetailView.as_view(), name='blog_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
]

furnitures/urls.py
from django.urls import path
from . import views

app_name = 'furnitures'

urlpatterns = [
    path('', views.FurnitureView.as_view(), name='furn_main'),
    path('create/', views.FurnitureCreateView.as_view(), name='furn_create'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('send_email/', views.EmailSendView.as_view(), name='send_email'),
    path('about/', views.AboutTemplateView.as_view(), name='about'),
    path('contact/', views.ContactTemplateView.as_view(), name='contact'),
]

web_project/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('furnitures/', include('furnitures.urls', namespace='furnitures')),
    path('', include('pages.urls', namespace='pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif"/>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Edgecut</title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet"/>

    <!-- font awesome style -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"/>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet"/>
</head>
<style>
    .detail-box {
        max-height: 200px; /* Установите желаемую максимальную высоту */
        overflow: hidden;
    }
</style>
<body class="{% block class %}{% endblock %}">
<div class="hero_area">
    <!-- header section strats -->
    <header class="header_section long_section px-0">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'pages:home' %}">
          <span>
            Edgecut
          </span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                    <ul class="navbar-nav  ">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'pages:home' %}">Home <span
                                    class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:about' %}"> About</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'furnitures:furn_main' %}">Furnitures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blog_home' %}">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:contact' %}">Contact Us</a>
                        </li>
                    </ul>
                </div>
                {% if user.is_authenticated %}
                    <div class="quote_btn-container">
                    <a href="{% url 'cart:cart_detail' %}">
                        <span>
                            Cart
                        </span>
                        <i class="bi bi-cart-fill"></i>
                        <sub>{{ cart|length }}</sub>
                        <sup>{{ cart.get_total_price }}$</sup>
                    </a>
                    <a href="#">
                    <span>
                        {{ user.username }}
                    </span>
                        <i class="fa fa-user" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'logout' %}">
                    <span>
                        Logout
                    </span>
                        <i class="bi bi-door-open-fill"></i>
                    </a>
                {% else %}
                    <div class="quote_btn-container">
                    <a href="{% url 'cart:cart_detail' %}">
                        <span>
                            Cart
                        </span>
                        <i class="bi bi-cart-fill"></i>
                        <sub>{{ cart|length }}</sub>
                        <sup>{{ cart.get_total_price }}$</sup>
                    </a>
                    <a href="{% url 'login' %}">
                    <span>
                        Login
                    </span>
                        <i class="fa fa-user" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'signup:signup' %}">
                    <span>
                        SignUp
                    </span>
                        <i class="fa fa-user-secret" aria-hidden="true"></i>
                    </a>
                {% endif %}
                <form class="form-inline">
                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </form>
                </div>
                </div>
        </nav>
    </header>
    <!-- end header section -->
    {% block content %}
    {% endblock %}
</div>
<!-- info section -->
<section class="info_section long_section">

    <div class="container">
        <div class="contact_nav">
            <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
            Call : +01 123455678990
          </span>
            </a>
            <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
            Email : demo@gmail.com
          </span>
            </a>
            <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
            Location
          </span>
            </a>
        </div>

        <div class="info_top ">
            <div class="row ">
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <div class="info_links">
                        <h4>
                            QUICK LINKS
                        </h4>
                        <div class="info_links_menu">
                            <a class="" href="{% url 'pages:home' %}">Home <span class="sr-only">(current)</span></a>
                            <a class="" href="{% url 'pages:about' %}"> About</a>
                            <a class="" href="#">Furniture</a>
                            <a class="" href="{% url 'blog:blog_home' %}">Blog</a>
                            <a class="" href="{% url 'pages:contact' %}">Contact Us</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3 mx-auto">
                    <div class="info_post">
                        <h5>
                            INSTAGRAM FEEDS
                        </h5>
                        <div class="post_box">
                            <div class="img-box">
                                <img src="{% static 'images/f1.png' %}" alt="">
                            </div>
                            <div class="img-box">
                                <img src="{% static 'images/f2.png' %}" alt="">
                            </div>
                            <div class="img-box">
                                <img src="{% static 'images/f3.png' %}" alt="">
                            </div>
                            <div class="img-box">
                                <img src="{% static 'images/f4.png' %}" alt="">
                            </div>
                            <div class="img-box">
                                <img src="{% static 'images/f5.png' %}" alt="">
                            </div>
                            <div class="img-box">
                                <img src="{% static 'images/f6.png' %}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info_form">
                        <h4>
                            SIGN UP TO OUR NEWSLETTER
                        </h4>
                        <form action="">
                            <input type="text" placeholder="Enter Your Email"/>
                            <button type="submit">
                                Subscribe
                            </button>
                        </form>
                        <div class="social_box">
                            <a href="">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end info_section -->


<!-- footer section -->
<footer class="footer_section">
    <div class="container">
        <p>
            &copy; <span id="displayYear"></span> All Rights Reserved By
            <a href="https://html.design/">Free Html Templates</a>
        </p>
    </div>
</footer>
<!-- footer section -->
<!-- jQery -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- bootstrap js -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- custom js -->
<script src="{% static 'js/custom.js' %}"></script>
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
<!-- End Google Map -->
</body>
</html>